import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='py-3 px-4'>
          <h2 className='font-semibold text-lg'>Clerkwise</h2>
        </header>
        {children}
        <footer className='p-4 pt-16'>
          <p className='text-center'>&copy; {new Date().getFullYear()} Full Stack Collective </p>
        </footer>
      </body>
    </html>
  );
}
